# Generated by Django 3.1.6 on 2021-02-04 16:24
import json
import os

from django.core.management import call_command
from django.db import migrations


def forwards_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")

    dirname = os.path.dirname(__file__)
    legacy = os.path.join(dirname, "..", "fixtures", "legacy.json")
    with open(legacy) as f:
        bookmarks = json.load(f)

    for b in bookmarks:
        fields = b["fields"]
        bookmark = Bookmark(
            title=fields["title"],
            description=fields["description"],
            url=fields["url"],
            tags=json.loads(fields["tags"]),
            created_at=fields["created_at"],
        )
        bookmark.save()


def reverse_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    Bookmark.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
