# Generated by Django 4.0.4 on 2022-05-24 15:47
from __future__ import annotations

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, size=None
                    ),
                ),
                (
                    "title_description_search",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="bookmarks_b_tags_65d16c_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title_description_search"], name="bookmarks_b_title_d_9107af_gin"
            ),
        ),
    ]
