# Generated by Django 4.0.4 on 2022-05-24 15:08
from __future__ import annotations

from django.db import migrations

TRIGGER_CREATE = """
    CREATE FUNCTION bookmark_trigger() RETURNS trigger as $$
    begin
        new.title_description_search :=
            setweight(to_tsvector('pg_catalog.english', coalesce(new.title, '')), 'A') ||
            setweight(to_tsvector('pg_catalog.english', coalesce(new.description, '')), 'B');
        return new;
    end
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER bookmark_update BEFORE INSERT OR UPDATE
        ON bookmarks_bookmark FOR EACH ROW EXECUTE FUNCTION bookmark_trigger();

    -- Force triggers to run and populate the title_description_search column.
    UPDATE bookmarks_bookmark SET id = id;
"""

TRIGGER_DROP = """
    DROP TRIGGER bookmark_update ON bookmarks_bookmark;
    DROP FUNCTION bookmark_trigger();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_CREATE, TRIGGER_DROP),
    ]
