# Generated by Django 4.0.4 on 2022-05-30 23:51
from __future__ import annotations

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_title_description_search_trigger"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title_description_search",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
