# Generated by Django 5.0.2 on 2024-02-26 12:30
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_alter_bookmark_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
