# Generated by Django 5.1.4 on 2024-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0005_bookmark_bookmarks_b_created_9a00a6_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
