# Generated by Django 5.1.4 on 2024-12-17 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0006_alter_bookmark_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookmark",
            name="bookmarks_b_tags_65d16c_gin",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="tags",
        ),
    ]
