# Generated by Django 5.1.4 on 2024-12-17 19:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0007_remove_bookmark_bookmarks_b_tags_65d16c_gin_and_more"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
