# Generated by Django 5.1.4 on 2024-12-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_bookmark_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-created',)},
        ),
    ]
