# Generated by Django 5.2 on 2025-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_options_and_more_squashed_0009_alter_bookmark_options'),
        ('upkeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='bookmarks',
            field=models.ManyToManyField(related_name='+', to='bookmarks.bookmark'),
        ),
    ]
