#!/bin/sh

# script/clean: Remove all build artifacts and cached dependencies.

set -e

cd "$(dirname "$0")/.."
source script/.config

if [ "$1" != "-y" ]; then
    echo "==> Aborting, run $0 with \"-y\" to confirm"
    exit -1
fi

if [ -d "$THIRD_PARTY_DIR" ]; then
    echo "==> Removing third party repos…"
    rm -rf $THIRD_PARTY_DIR
fi

echo "==> Removing files in .gitignore…"
git clean -dfX -n

echo "==> Removing poetry environments…"
poetry env remove --all
