#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."
source script/.config

script/bootstrap

echo "==> Updating Tailwind CSS…"
npx postcss puka/static/css/base.css -o puka/static/css/main.css
NODE_ENV=production npx postcss puka/static/css/base.css -o puka/static/css/main.min.css

echo "==> Updating HTMX…"
cp node_modules/htmx.org/dist/htmx.min.js puka/static/js/
cp node_modules/htmx.org/dist/ext/class-tools.js puka/static/js/

echo "==> Updating _Hyperscript…"
cp "$THIRD_PARTY_DIR"/_hyperscript/dist/_hyperscript.min.js puka/static/js/
