# Generated by Django 5.1.6 on 2025-02-18 01:28

from django.db import migrations

TRIGGER_CREATE = """
    CREATE FUNCTION item_trigger() RETURNS trigger as $$
    begin
        new.name_notes_search :=
            setweight(to_tsvector('pg_catalog.english', coalesce(new.name, '')), 'A') ||
            setweight(to_tsvector('pg_catalog.english', coalesce(new.notes, '')), 'B');
        return new;
    end
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER item_update BEFORE INSERT OR UPDATE
        ON stuff_item FOR EACH ROW EXECUTE FUNCTION item_trigger();

    -- Force triggers to run and populate the name_notes_search column.
    UPDATE stuff_item SET id = id;
"""

TRIGGER_DROP = """
    DROP TRIGGER item_update ON stuff_item;
    DROP FUNCTION item_trigger();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_CREATE, TRIGGER_DROP),
    ]
