# Generated by Django 5.1.6 on 2025-02-18 01:25

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_remove_product_category_product_tags_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_notes_search',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
