# Generated by Django 5.1.6 on 2025-02-18 01:28

from django.db import migrations

TRIGGER_CREATE = """
    CREATE FUNCTION product_trigger() RETURNS trigger as $$
    begin
        new.name_notes_search :=
            setweight(to_tsvector('pg_catalog.english', coalesce(new.name, '')), 'A') ||
            setweight(to_tsvector('pg_catalog.english', coalesce(new.notes, '')), 'B');
        return new;
    end
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER product_update BEFORE INSERT OR UPDATE
        ON stuff_product FOR EACH ROW EXECUTE FUNCTION product_trigger();

    -- Force triggers to run and populate the name_notes_search column.
    UPDATE stuff_product SET id = id;
"""

TRIGGER_DROP = """
    DROP TRIGGER product_update ON stuff_product;
    DROP FUNCTION product_trigger();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_product_name_notes_search'),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_CREATE, TRIGGER_DROP),
    ]
