on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Run Puka Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix flake check`
        run: nix flake check
